name: Create new issue via dispatched workflow trigger from other repo

on:
  workflow_dispatch:

jobs:
  open-issue:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - run: |
          gh issue --repo ${{ github.repository }} \
            create --title "Issue title" --body "Issue body"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Check out repository
#         uses: actions/checkout@v2
#       - name: Create Issue
#         run: |
#           curl -L \
#             -X POST \
#             -H "Accept: application/vnd.github+json" \
#             -H "X-GitHub-Api-Version: 2022-11-28" \
#             -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
#             https://api.github.com/repos/minaelee/test-workflows2/issues \
#             -d '{"title":"test","body":"test"}'
